{{- range $name, $config := .Values.configs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  labels:
    {{- include "replik8s.labels" $ | nindent 4 }}
    replik8s.gpte.redhat.com/source: ''
data:
  spec: |
    {{- if eq (typeOf $config) "string" -}}
    {{- $config | nindent 4 }}
    {{- else -}}
    {{- $config | toYaml | nindent 4 }}
    {{- end }}
{{- end }}
