{{- range $name, $kubeConfig := .Values.kubeConfigs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "replik8s.labels" $ | nindent 4 }}
data:
  kubeconfig.yaml: >-
    {{ if eq (typeOf $kubeConfig) "string" -}}
    {{- $kubeConfig | b64enc -}}
    {{- else -}}
    {{- $kubeConfig | toYaml | b64enc -}}
    {{ end }}
{{- end }}
