{{- range $name, $kubeConfig := .Values.kubeConfigs }}
{{- if (and (ne (typeOf $kubeConfig) "string") $kubeConfig.bitwardenSecret) -}}
---
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: {{ $name }}
spec:
  data:
    kubeconfig.yaml:
      secret: {{ $kubeConfig.bitwardenSecret }}
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "replik8s.labels" $ | nindent 4 }}
data:
  kubeconfig.yaml: >-
    {{ if eq (typeOf $kubeConfig) "string" -}}
    {{- $kubeConfig | b64enc -}}
    {{- else -}}
    {{- $kubeConfig | toYaml | b64enc -}}
    {{ end }}
{{- end }}
{{- end }}
