{{- if and .Values.deploy .Values.persistentVolume.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "replik8s.name" . }}
  labels:
    {{- include "replik8s.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.persistentVolume.spec | nindent 2 }}
{{- end -}}
