apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "replik8s.name" . }}
  labels:
    {{- include "replik8s.labels" . | nindent 4 }}
rules:
- apiGroups:
  - {{ .Values.api.group }}
  resources:
  - replicationsources
  - replicationsources/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
