apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "replik8s-openshift-build.name" . }}
  labels:
    {{- include "replik8s-openshift-build.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false
