---
apiVersion: v1
kind: ConfigMap
metadata:
  name: babylon
  labels:
    replik8s.gpte.redhat.com/source: ''
data:
  spec: |
    kubeConfig:
      secret: kubeconfig
    resources:
    - apiVersion: anarchy.gpte.redhat.com/v1
      kind: AnarchySubject
    - apiVersion: anarchy.gpte.redhat.com/v1
      kind: AnarchyAction
    - apiVersion: poolboy.gpte.redhat.com/v1
      kind: ResourceClaim
    - apiVersion: poolboy.gpte.redhat.com/v1
      kind: ResourceHandle
      namespace: poolboy
