---
apiVersion: v1
kind: ConfigMap
metadata:
  name: operators
  labels:
    replik8s.gpte.redhat.com/source: ''
data:
  spec: |
    kubeConfig:
      secret: kubeconfig
    resources:
    - apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
    - apiVersion: operators.coreos.com/v1alpha1
      kind: ClusterServiceVersion
    - apiVersion: operators.coreos.com/v1alpha1
      kind: InstallPlan
    - apiVersion: operators.coreos.com/v1
      kind: Operator
    - apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
    - apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
